### ISSUE TITLE
Could not find gem 'webpay_interswitch (>= 0) ruby' in the gems available on this machine.

### ISSUE THREAD

**Issue by shoaibmalik786** [vinsol/webpay_interswitch#1]
This is not available in gems

**Comment by ShubhamGupta** [comment]
Hey @shoaibmalik786 We have not released this gem yet as we couldn't test on production. If you want to use this on production, please let me know.

**Comment by shoaibmalik786** [comment]
Yes, i need this gem to integrate in my app. It is giving gemfile error

**Comment by ShubhamGupta** [comment]
@shoaibmalik786 You can use `Bundler's` `git` functionality to get the bleeding edge. Simply add to your Gemfile:

`gem 'webpay_interswitch', git: 'https://github.com/vinsol/webpay_interswitch.git'`

Do let us know if this works so we can close the issue.

**Comment by shoaibmalik786** [comment]
It is still throw the same exception

**Comment by bansalakhil** [comment]
Hi @shoaibmalik786,

We released this gem today. Can you try "gem 'webpay_interswitch', '~> 1.1'" once and do bundle install. If it doesn't work, please share the exact error your get

**Comment by ShubhamGupta** [comment]
Hope this has been resolved. Closing the issue.
